#include <iostream>
using namespace std;
main()
{  int aprice, cprice, numa, numc, perc, amount, charity, rem;
   string name;
   cout<< " \nEnter the movie name: ";
   cin>> name;
   cout<< "Enter the adult ticket price (in $): ";
   cin>> aprice;
   cout<<"Enter the child ticket price (in $): ";
   cin>> cprice;
   cout<<"Enter the number of adult tickets sold: ";
   cin>> numa;
   cout<<"Enter the number of child tickets sold: ";
   cin>> numc;
   cout<<"Enter the percentage of the amount to be donated to charity: ";
   cin>> perc;
   cout<< " \nMovie: "<<name<<endl;
   amount= (aprice*numa) + (cprice*numc);
   cout<< "Total amount generated by tickets: $"<<amount<< endl;
   charity= amount*perc/100;
   cout<<"Donation to charity: $"<<charity<< endl;
   rem= amount-charity;
   cout<<"Remaining amount after charity: $"<<rem<<endl;
}